/* 中医Buddy · 诊断规则数据 (A) — 移植自 diagnostic_rules.dart */
window.RULES = window.RULES || {};
Object.assign(window.RULES, {
  symptomWeights: {
    pulse_float: 0.9, headache: 0.8, neck_stiff: 0.8, chills: 0.9, body_pain: 0.7,
    no_sweat: 0.85, fever_chills: 0.9, high_fever: 0.9, no_chills: 0.85, sweating: 0.7,
    thirst_strong: 0.8, pulse_large: 0.8, constipated: 0.75, bitter_mouth: 0.9,
    dry_throat: 0.85, dizziness: 0.7, alternating_chills: 0.9, chest_flank_fullness: 0.85,
    nausea_vomiting: 0.7, abdominal_pain: 0.8, diarrhea: 0.75, no_thirst: 0.8,
    tongue_pale_coated_white: 0.85, drowsy: 0.95, pulse_thin_weak: 0.9, cold_limbs: 0.85,
    clear_urine: 0.7, diarrhea_clear: 0.8, thirst_no_drink: 0.9, upper_heat_lower_cold: 0.85,
    hunger_no_eat: 0.8, vomit_roundworm: 0.95,
  },

  combinedPatterns: [
    { meridians: ['太阳', '阳明'], condition: 'sun_symptoms + yangming_symptoms', formula: '葛根汤', description: '太阳与阳明合病，必自下利', source: '伤寒论第32条' },
    { meridians: ['太阳', '少阳'], condition: 'sun_symptoms + shao_yang_symptoms', formula: '柴胡桂枝汤', description: '太阳少阳合病，发热微恶寒，支节烦痛，微呕', source: '伤寒论第109条' },
    { meridians: ['少阳', '阳明'], condition: 'shao_yang_symptoms + yangming_symptoms', formula: '大柴胡汤', description: '少阳阳明合病，呕不止，心下急', source: '伤寒论第116条' },
    { meridians: ['太阳', '阳明', '少阳'], condition: 'three_yang_symptoms', formula: '小柴胡汤', description: '三阳并病，必须合解少阳', source: '伤寒论第99条' },
    { meridians: ['太阴', '少阴'], condition: 'taiyin_symptoms + shaoyin_symptoms', formula: '四逆汤', description: '太阴少阴合病，脾肾阳虚', source: '临床经验' },
    { meridians: ['太阳', '阳明'], condition: 'sun+yangming_vomit', formula: '葛根加半夏汤', description: '太阳阳明合病，不下利但呕者', source: '伤寒论第37条' },
    { meridians: ['太阳', '阳明'], condition: 'sun+yangming_chest_full', formula: '麻黄汤', description: '太阳阳明合病，喘而胸满', source: '伤寒论第40条' },
    { meridians: ['太阳', '少阳'], condition: 'sun+shaoyang_diarrhea', formula: '黄芩汤', description: '太阳少阳合病，自下利', source: '伤寒论第172条' },
    { meridians: ['太阳', '少阳'], condition: 'sun+shaoyang_vomit', formula: '黄芩加半夏生姜汤', description: '太阳少阳合病，呕者', source: '伤寒论第172条' },
    { meridians: ['少阳', '阳明'], condition: 'shaoyang+yangming_tidal_fever', formula: '柴胡加芒硝汤', description: '少阳阳明合病，潮热', source: '伤寒论第104条' },
    { meridians: ['阳明', '少阴'], condition: 'yangming+shaoyin_urgent', formula: '大承气汤', description: '少阴病得之二三日，口燥咽干者，急下之', source: '伤寒论第320条' },
    { meridians: ['厥阴', '少阳'], condition: 'jueyin+shaoyang', formula: '乌梅丸', description: '厥阴少阳合病，寒热错杂', source: '临床经验' },
    { meridians: ['太阳', '阳明'], condition: 'sun+yangming_unresolved', formula: '桂枝汤', description: '二阳并病，太阳证未罢，面色缘缘正赤，当小发汗', source: '伤寒论第53条' },
    { meridians: ['太阳', '阳明', '少阳'], condition: 'three_yang_sleep', formula: '小柴胡汤', description: '三阳合病，脉浮大上关上，但欲眠睡，目合则汗', source: '伤寒论第268条' },
    { meridians: ['太阳', '阳明'], condition: 'sun+yangming_interior_heat', formula: '大青龙汤', description: '太阳阳明合病，表寒里热俱实，无汗恶寒身痛+口渴烦躁', source: '伤寒论第38条' },
    { meridians: ['太阳', '少阴'], condition: 'sun+shaoyin_two_cold', formula: '麻黄附子细辛汤', description: '太阳少阴两感，始得之，发热恶寒脉沉', source: '伤寒论第301条' },
    { meridians: ['少阳', '太阴'], condition: 'shaoyang+taiyin', formula: '柴胡桂枝干姜汤', description: '少阳太阴合病，往来寒热+腹满便溏食不下', source: '伤寒论第147条' },
    { meridians: ['太阳', '太阴'], condition: 'sun+taiyin', formula: '桂枝人参汤', description: '太阳太阴并病，里虚寒+表证未罢', source: '伤寒论第163条' },
    { meridians: ['太阳', '阳明'], condition: 'sun+yangming_diarrhea_heat', formula: '葛根芩连汤', description: '太阳阳明合病，表证轻里热重，下利臭秽', source: '伤寒论第34条' },
  ],

  differentialDiagnoses: {
    '太阳中风_vs_伤寒': { name1: '太阳中风', formula1: '桂枝汤', name2: '太阳伤寒', formula2: '麻黄汤', keyDifference: '有汗无汗', details: { '中风': '有汗、恶风、脉浮缓', '伤寒': '无汗、恶寒、脉浮紧' } },
    '苓桂术甘_vs_真武': { name1: '苓桂术甘汤证', formula1: '苓桂术甘汤', name2: '真武汤证', formula2: '真武汤', keyDifference: '水饮位置与阳虚程度', details: { '苓桂术甘': '中膈水饮、起则头眩、脉沉紧', '真武': '全身阳虚、躺着也晕、脉细小而迟、脚冷' } },
    '大青龙_vs_小青龙': { name1: '大青龙汤证', formula1: '大青龙汤', name2: '小青龙汤证', formula2: '小青龙汤', keyDifference: '里热里寒', details: { '大青龙': '表寒里热、烦躁、黄痰', '小青龙': '表寒里寒、白沫痰、不渴' } },
    '白虎_承气': { name1: '白虎汤证', formula1: '白虎汤', name2: '承气汤证', formula2: '承气汤', keyDifference: '大便是否燥结', details: { '白虎': '大热大渴、大便正常', '承气': '腹满燥实、大便不通' } },
    '小柴胡_vs_大柴胡': { name1: '小柴胡汤证', formula1: '小柴胡汤', name2: '大柴胡汤证', formula2: '大柴胡汤', keyDifference: '有无便秘', details: { '小柴胡': '口苦咽干目眩、往来寒热、胸胁苦满、大便正常', '大柴胡': '呕不止、心下急、郁郁微烦、大便秘结' } },
    '桂枝加附子_vs_真武': { name1: '桂枝加附子汤证', formula1: '桂枝加附子汤', name2: '真武汤证', formula2: '真武汤', keyDifference: '表虚程度与阳虚范围', details: { '桂枝加附子': '表阳虚、汗出不止、恶风、四肢微急', '真武': '里阳虚、心悸头眩、身瞤动、小便不利、四肢沉重' } },
    '四逆_vs_通脉四逆': { name1: '四逆汤证', formula1: '四逆汤', name2: '通脉四逆汤证', formula2: '通脉四逆汤', keyDifference: '有无阴盛格阳', details: { '四逆': '四肢厥逆、脉微欲绝、下利清谷', '通脉四逆': '身反不恶寒、面色赤、阴盛格阳于外' } },
    '理中_vs_四逆': { name1: '理中汤证', formula1: '理中汤', name2: '四逆汤证', formula2: '四逆汤', keyDifference: '脾虚寒湿 vs 脾肾俱虚', details: { '理中': '腹满吐利、食不下、时腹自痛、病在中焦', '四逆': '四肢厥逆、脉微欲绝、下利清谷、病在下焦' } },
    '麻黄_vs_麻杏甘石': { name1: '麻黄汤证', formula1: '麻黄汤', name2: '麻杏甘石汤证', formula2: '麻杏甘石汤', keyDifference: '表寒闭肺 vs 肺热壅盛', details: { '麻黄': '恶寒无汗、体痛呕逆、脉浮紧、咳喘', '麻杏甘石': '汗出而喘、无大热、口渴、痰黄' } },
    '五苓_vs_猪苓': { name1: '五苓散证', formula1: '五苓散', name2: '猪苓汤证', formula2: '猪苓汤', keyDifference: '水气不化 vs 阴虚水热', details: { '五苓': '口渴、小便不利、水入则吐、脉浮', '猪苓': '渴欲饮水、小便不利、心烦不得眠、咳呕' } },
    '茯苓四逆_vs_干姜附子': { name1: '茯苓四逆汤证', formula1: '茯苓四逆汤', name2: '干姜附子汤证', formula2: '干姜附子汤', keyDifference: '阴阳两虚烦躁 vs 纯阳虚', details: { '茯苓四逆': '烦躁、四逆、阴阳两虚、水气上冲', '干姜附子': '昼日烦躁不得眠、夜而安静、脉沉微、纯阳虚' } },
    '真武_vs_附子汤': { name1: '真武汤证', formula1: '真武汤', name2: '附子汤证', formula2: '附子汤', keyDifference: '阳虚水泛 vs 气虚骨痛', details: { '真武': '心下悸、头眩、身瞤动、振振欲擗地、阳虚水泛', '附子': '身体痛、手足寒、骨节痛、气虚寒凝' } },
    '桂枝加附子_vs_桂枝去芍药_vs_新加汤': { name1: '桂枝加附子汤证', formula1: '桂枝加附子汤', name2: '桂枝去芍药/新加汤', formula2: '桂枝去芍药汤/桂枝新加汤', keyDifference: '汗不止 vs 胸满 vs 身痛', details: { '桂枝加附子': '汗出不止、恶风、小便难、四肢微急（收表）', '桂枝去芍药': '脉促、胸满（心脏病不用芍药）', '桂枝新加汤': '身疼痛、脉沉迟（津液伤、重芍药加人参）' } },
    '栀子豉_vs_黄连阿胶': { name1: '栀子豉汤证', formula1: '栀子豉汤', name2: '黄连阿胶汤证', formula2: '黄连阿胶汤', keyDifference: '余热虚烦 vs 心血不足', details: { '栀子豉': '虚烦不得眠、反复颠倒、心中懊憹、舌淡黄脉无力', '黄连阿胶': '心中烦不得卧、中空脉、舌黄干、心肾不交' } },
    '半夏泻心_vs_生姜泻心_vs_甘草泻心': { name1: '半夏泻心汤证', formula1: '半夏泻心汤', name2: '生姜/甘草泻心汤证', formula2: '生姜泻心汤/甘草泻心汤', keyDifference: '痞证三型鉴别', details: { '半夏泻心': '心下痞+腹痛+肠鸣（治痞主方）', '生姜泻心': '心下痞+严重下利+肠鸣重（重用生姜排水）', '甘草泻心': '心下痞+恶心、无肠鸣无腹痛（去黄连）' } },
    '乌梅丸_vs_当归四逆': { name1: '乌梅丸证', formula1: '乌梅丸', name2: '当归四逆汤证', formula2: '当归四逆汤', keyDifference: '寒热错杂 vs 血虚寒凝', details: { '乌梅丸': '消渴、气上撞心、心中疼热、饥而不欲食（寒热错杂）', '当归四逆': '手足厥寒、脉细欲绝、月经不来（血虚寒凝）' } },
    '栀子豉_vs_白虎': { name1: '栀子豉汤证', formula1: '栀子豉汤', name2: '白虎汤证', formula2: '白虎汤', keyDifference: '虚热 vs 实热', details: { '栀子豉': '虚烦、舌苔淡黄、脉无力重按不见（余热未尽）', '白虎': '大热大渴、舌苔黄且干燥、脉洪大（阳明实热）' } },
    '四逆_vs_茯苓四逆_vs_干姜附子': { name1: '四逆汤证', formula1: '四逆汤', name2: '茯苓四逆/干姜附子', formula2: '茯苓四逆汤/干姜附子汤', keyDifference: '回阳三方鉴别', details: { '四逆': '四逆、下利清谷、脉微欲绝（回阳救逆基础方）', '茯苓四逆': '四逆+烦躁（阴阳两虚，茯苓为君）', '干姜附子': '昼烦夜安、脉沉微（纯阳虚，去甘草之缓）' } },
    '麻黄附子细辛_vs_麻黄附子甘草': { name1: '麻黄附子细辛汤证', formula1: '麻黄附子细辛汤', name2: '麻黄附子甘草汤证', formula2: '麻黄附子甘草汤', keyDifference: '少阴表证：峻烈去寒 vs 缓和利尿', details: { '麻附细辛': '里寒极盛、阴寒水肿、小便难、壮肾阳去里寒', '麻附甘草': '肾阳虚水肿、脉沉小、甘草缓和、利尿消肿' } },
    '白虎_vs_白虎人参': { name1: '白虎汤证', formula1: '白虎汤', name2: '白虎加人参汤证', formula2: '白虎加人参汤', keyDifference: '津液亏损程度', details: { '白虎': '纯阳明经热、大热大汗、津液未大伤', '白虎人参': '大烦渴不解、脉洪大、津液明显亏损、高热汗出' } },
    '小建中_vs_理中': { name1: '小建中汤证', formula1: '小建中汤', name2: '理中汤证', formula2: '理中汤', keyDifference: '虚寒腹痛 vs 脾虚寒湿', details: { '小建中': '隐痛喜按、面色苍白、食欲不振、脾津液不足', '理中': '腹满吐利、食不下、舌苔白厚、寒湿困脾' } },
    '桃核承气_vs_抵当汤': { name1: '桃核承气汤证', formula1: '桃核承气汤', name2: '抵当汤证', formula2: '抵当汤', keyDifference: '蓄血轻重：小便带血如狂 vs 小便自利发狂', details: { '桃核承气': '热结膀胱、其人如狂、小便带血、少腹急结', '抵当': '小便自利、大便黑、发狂善忘、少腹剧痛固定' } },
    '十枣_vs_陷胸': { name1: '十枣汤证', formula1: '十枣汤', name2: '大/小陷胸汤证', formula2: '大陷胸汤/小陷胸汤', keyDifference: '水饮 vs 痰实', details: { '十枣': '肺积水满、不能卧、悬饮留饮', '大陷胸': '热实结胸、痰堵胸腔、热痰实证', '小陷胸': '轻症结胸、抽烟咳喘、黄痰在胸腔' } },
    '麻子仁_vs_承气': { name1: '麻子仁丸证', formula1: '麻子仁丸', name2: '承气汤证', formula2: '承气汤', keyDifference: '虚秘 vs 热秘', details: { '麻子仁': '虚秘、宿食堵小肠较轻、润下缓通', '承气': '热秘、宿食堵小肠较重、攻下峻猛' } },
    '吴茱萸_vs_四逆': { name1: '吴茱萸汤证', formula1: '吴茱萸汤', name2: '四逆汤证', formula2: '四逆汤', keyDifference: '厥阴肝虚 vs 少阴心肾阳虚', details: { '吴茱萸': '头痛呕吐、吐涎沫、呕酸、肝虚寒', '四逆': '脉微细但欲寐、手足逆冷、心肾阳虚' } },
    '当归四逆_vs_四逆': { name1: '当归四逆汤证', formula1: '当归四逆汤', name2: '四逆汤证', formula2: '四逆汤', keyDifference: '血虚寒凝 vs 阳气衰微', details: { '当归四逆': '手足厥寒、脉细欲绝、月经不来、血虚寒凝', '四逆': '手足逆冷至膝肘、脉微细但欲寐、阳气衰微' } },
    '承气_vs_麻子仁': { name1: '承气汤证', formula1: '承气汤', name2: '麻子仁丸证', formula2: '麻子仁丸', keyDifference: '热秘 vs 虚秘', details: { '承气': '热秘、宿食堵小肠较重、攻下峻猛', '麻子仁': '虚秘、润下缓通' } },
  },

  formulaModifications: {
    '桂枝汤': [
      { condition: '兼咳喘', symptom: 'cough', type: 'add', herbName: '厚朴、杏仁', resultFormula: '桂枝加厚朴杏仁汤', description: '加厚朴、杏仁以降气平喘' },
      { condition: '兼项背强', symptom: 'neck_stiff', type: 'add', herbName: '葛根', resultFormula: '桂枝加葛根汤', description: '加葛根以舒经通络' },
      { condition: '兼汗多心悸', symptom: 'palpitations', type: 'add', herbName: '龙骨、牡蛎', resultFormula: '桂枝加龙骨牡蛎汤', description: '加龙骨、牡蛎以潜阳安神' },
      { condition: '兼胸满', symptom: 'chest_fullness', type: 'remove', herbName: '芍药', resultFormula: '桂枝去芍药汤', description: '去芍药以免酸收敛邪（心脏病不用芍药）' },
      { condition: '兼身痛脉沉迟', symptom: 'body_pain', type: 'add', herbName: '人参', resultFormula: '桂枝新加汤', description: '加重芍药、生姜，加人参以补津液止痛' },
    ],
    '小柴胡汤': [
      { condition: '兼便秘', symptom: 'constipation', type: 'add', herbName: '大黄、枳实', resultFormula: '大柴胡汤', description: '加大黄、枳实以攻下' },
      { condition: '兼口渴', symptom: 'thirst_strong', type: 'add', herbName: '栝蒌根', resultFormula: '柴胡去半夏加栝蒌汤', description: '去半夏加栝蒌根以生津止渴' },
    ],
    '真武汤': [
      { condition: '兼咳', symptom: 'cough', type: 'add', herbName: '五味子、细辛、干姜', resultFormula: '', description: '加五味子、细辛、干姜以温肺止咳' },
      { condition: '兼下利', symptom: 'diarrhea', type: 'replace', herbName: '芍药', replaceWith: '干姜', resultFormula: '', description: '去芍药加干姜以温中止利' },
    ],
    '四逆汤': [
      { condition: '兼脉绝', symptom: 'pulse_gone', type: 'add', herbName: '人参', resultFormula: '四逆加人参汤', description: '加人参以益气复脉' },
      { condition: '兼阴盛格阳', symptom: 'upper_heat_lower_cold', type: 'add', herbName: '葱白', resultFormula: '通脉四逆汤', description: '加葱白以通阳破阴' },
      { condition: '兼烦躁', symptom: 'irritability', type: 'add', herbName: '茯苓、人参', resultFormula: '茯苓四逆汤', description: '加茯苓六两、人参一两以利水宁心（烦躁为辨证关键）' },
    ],
    '理中汤': [
      { condition: '兼呕吐多', symptom: 'vomiting', type: 'add', herbName: '生姜', resultFormula: '', description: '加生姜以和胃止呕' },
      { condition: '兼下利多', symptom: 'diarrhea', type: 'add', herbName: '附子', resultFormula: '附子理中汤', description: '加附子以温阳止利' },
    ],
    '麻黄汤': [
      { condition: '兼烦躁', symptom: 'irritability', type: 'add', herbName: '石膏', resultFormula: '大青龙汤', description: '加石膏以清里热（表寒里热）' },
    ],
    '白虎汤': [
      { condition: '兼气虚', symptom: 'weakness', type: 'add', herbName: '人参', resultFormula: '白虎加人参汤', description: '加人参以益气生津' },
    ],
    '麻黄附子细辛汤': [
      { condition: '兼水肿轻症', symptom: 'edema', type: 'replace', herbName: '细辛', replaceWith: '甘草', resultFormula: '麻黄附子甘草汤', description: '去细辛加甘草，缓和利尿消肿' },
    ],
    '小建中汤': [
      { condition: '兼心悸', symptom: 'palpitations', type: 'add', herbName: '炙甘草', resultFormula: '炙甘草汤', description: '重用炙甘草以补心血（脉结代）' },
    ],
    '吴茱萸汤': [
      { condition: '兼头痛剧烈', symptom: 'headache', type: 'add', herbName: '川芎', resultFormula: '', description: '加川芎以活血止痛' },
    ],
    '当归四逆汤': [
      { condition: '兼内有久寒', symptom: 'chronic_cold', type: 'add', herbName: '吴茱萸、生姜', resultFormula: '当归四逆加吴茱萸生姜汤', description: '加吴茱萸、生姜以温里散寒' },
    ],
    '栀子豉汤': [
      { condition: '兼少气', symptom: 'weakness', type: 'add', herbName: '甘草', resultFormula: '栀子甘草豉汤', description: '加甘草以益气' },
      { condition: '兼呕吐', symptom: 'vomiting', type: 'add', herbName: '生姜', resultFormula: '栀子生姜豉汤', description: '加生姜以止呕' },
    ],
  },

  careAdvice: {
    '太阳': { diet: ['禁生冷、粘滑、肉面、五辛、酒酪', '宜热稀粥助药力', '宜清淡易消化'], rest: ['被子盖好躺二小时', '遍身漐漐微汗为佳', '不可令如水流漓'], moxibustion: ['可灸风池、风府、大椎'], avoid: ['不可吹风', '不可冷水洗澡'] },
    '阳明': { diet: ['禁辛辣燥热', '宜清淡流质', '大便通后渐增饮食'], rest: ['高热时卧床休息', '保持室内通风'], moxibustion: ['实热证不可灸', '白虎汤证可灸足三里健胃'], avoid: ['不可发汗', '不可温灸（实热证时）'] },
    '少阳': { diet: ['禁发汗、吐、下', '宜疏肝理气之品', '少食多餐'], rest: ['保持情志舒畅', '避免熬夜'], moxibustion: ['可灸阳陵泉、期门'], avoid: ['不可发汗（发汗则谵语）', '不可吐下（吐下则悸而惊）'] },
    '太阴': { diet: ['禁寒凉生冷', '宜温热健脾', '理中汤类温服'], rest: ['腹部保暖', '避免受寒'], moxibustion: ['可灸中脘、足三里、脾俞', '虚寒证宜灸'], avoid: ['不可攻下', '攻下会更胸下结硬'] },
    '少阴': { diet: ['禁一切寒凉', '宜温阳回逆', '四逆汤类温服'], rest: ['充分休息', '避免过劳', '保暖'], moxibustion: ['可灸关元、气海、命门', '重灸回阳'], avoid: ['不可发汗', '不可攻下', '避免受寒'] },
    '厥阴': { diet: ['寒热错杂需寒热并用', '禁生冷', '宜乌梅丸'], rest: ['调畅情志', '避免郁怒'], moxibustion: ['可灸太冲、期门', '寒证可灸关元'], avoid: ['不可单独攻下', '不可单独发汗'] },
  },

  tonguePulseWeights: {
    tongue_coating: { '薄白': 0.0, '白厚': 0.3, '黄薄': 0.3, '黄厚': 0.5, '灰黑': 0.4, '无苔': 0.3 },
    tongue_shape: { '淡红': 0.0, '淡白': 0.3, '红': 0.3, '绛紫': 0.4, '胖大': 0.3, '瘦小': 0.3, '齿痕': 0.3 },
    pulse: { '浮': 0.5, '沉': 0.4, '迟': 0.4, '数': 0.4, '滑': 0.3, '涩': 0.3, '弦': 0.4, '紧': 0.4, '缓': 0.3, '弱': 0.3, '微': 0.5, '细': 0.4, '洪': 0.5, '实': 0.4, '虚': 0.4 },
  },

  tongueCoatingOptions: ['薄白', '白厚', '黄薄', '黄厚', '灰黑', '无苔'],
  tongueShapeOptions: ['淡红', '淡白', '红', '绛紫', '胖大', '瘦小', '齿痕'],
  pulseOptions: ['浮', '沉', '迟', '数', '滑', '涩', '弦', '紧', '缓', '弱', '微', '细', '洪', '实', '虚'],

  chiefComplaints: [
    { key: 'fever_chills', label: '发烧怕冷', emoji: '🤒', description: '发热同时怕冷，太阳表证' },
    { key: 'fever_only', label: '只发烧不怕冷', emoji: '🌡️', description: '发热但不怕冷，阳明或温病' },
    { key: 'chills_only', label: '只怕冷不发烧', emoji: '🥶', description: '畏寒但不发热，太阴少阴' },
    { key: 'alternating', label: '忽冷忽热', emoji: '🔄', description: '一阵冷一阵热，少阳证' },
    { key: 'upper_heat_lower_cold', label: '上热下寒', emoji: '☯️', description: '口干口苦但手脚冰，厥阴' },
    { key: 'headache', label: '头痛', emoji: '🤕', description: '头部疼痛，需辨经络' },
    { key: 'neck_stiff', label: '脖子僵硬', emoji: '🦴', description: '项背强几几，太阳经输不利' },
    { key: 'body_pain', label: '全身酸痛', emoji: '💪', description: '骨节疼痛，伤寒表实' },
    { key: 'cough', label: '咳嗽气喘', emoji: '😷', description: '肺系症状，需辨寒热' },
    { key: 'abdominal_pain', label: '肚子痛', emoji: '🤢', description: '腹痛，需辨虚实寒热' },
    { key: 'diarrhea', label: '拉肚子', emoji: '💨', description: '下利，需辨寒热' },
    { key: 'constipation', label: '便秘', emoji: '😰', description: '大便不通，阳明腑实' },
    { key: 'vomiting', label: '呕吐', emoji: '🤮', description: '呕吐，少阳太阴皆有' },
    { key: 'bitter_mouth', label: '嘴苦', emoji: '😖', description: '口苦咽干，少阳胆火' },
    { key: 'fatigue', label: '很累很困', emoji: '😴', description: '精神疲倦但欲寐，少阴' },
    { key: 'insomnia', label: '睡不着烦躁', emoji: '😫', description: '失眠心烦，少阴热化' },
    { key: 'palpitation', label: '心悸心慌', emoji: '💗', description: '心跳异常，心阳虚' },
    { key: 'dizziness', label: '头晕目眩', emoji: '💫', description: '眩晕，水饮或少阳' },
    { key: 'cold_limbs', label: '手脚冰冷', emoji: '🧊', description: '四肢厥冷，阳虚' },
    { key: 'edema', label: '水肿', emoji: '💧', description: '身体浮肿，阳虚水泛' },
    { key: 'joint_pain', label: '关节疼痛', emoji: '🦴', description: '风湿痹证' },
    { key: 'skin', label: '皮肤问题', emoji: '🩹', description: '疮疡、瘙痒、过敏' },
    { key: 'urination', label: '小便异常', emoji: '🚽', description: '尿频、尿痛、不利' },
    { key: 'menstrual', label: '月经问题', emoji: '🩸', description: '痛经、量少、不调' },
  ],

  temperaturePatterns: [
    { key: 'fever_chills', label: '发热 + 怕冷', description: '发烧的同时也怕冷，太阳表证', targetMeridian: '太阳' },
    { key: 'fever_no_cold', label: '只发热不怕冷', description: '发烧但不怕冷，反而怕热。但热不寒为阳明。', targetMeridian: '阳明' },
    { key: 'chills_no_fever', label: '只怕冷不发热', description: '畏寒但体温不高，里虚寒证', targetMeridian: '太阴/少阴' },
    { key: 'alternating_chills_fever', label: '一阵冷一阵热', description: '忽冷忽热像打摆子，半表半里', targetMeridian: '少阳' },
    { key: 'upper_heat_lower_cold', label: '上热下寒', description: '上面口干口苦，下面手脚冰冷，寒热错杂', targetMeridian: '厥阴' },
    { key: 'fever_thirst_no_cold', label: '发热而渴，不恶寒', description: '发热口渴但不怕冷，温病。津液不足。', targetMeridian: '太阳' },
  ],
  temperatureToMeridian: {
    fever_chills: '太阳', fever_no_cold: '阳明', chills_no_fever: '太阴/少阴',
    alternating_chills_fever: '少阳', upper_heat_lower_cold: '厥阴', fever_thirst_no_cold: '太阳',
  },

  tenQuestions: [
    { key: 'gender', question: '请问您的性别？（影响月经问题的问诊）', options: ['男', '女'] },
    { key: 'sleep', question: '【一问睡眠】晚上能一觉到天亮吗？几点醒？', options: ['一觉到天亮', '半夜1-3点醒', '半夜3-5点醒', '整夜睡不着', '多梦易醒', '嗜睡但睡不够'] },
    { key: 'appetite', question: '【二问胃口】三餐正常吗？有没有特别想吃或不想吃的？', options: ['正常三餐', '没有胃口', '特别能吃', '饿但不想吃（厥阴）', '想吃冷的', '想吃热的', '食不下（太阴）'] },
    { key: 'stool', question: '【三问大便】每天有大便吗？成形还是稀的？颜色？', options: ['每天有，成形', '便秘，好几天一次', '稀/拉肚子', '先硬后稀', '水样便', '便脓血', '下利清谷（完谷不化）'] },
    { key: 'urine', question: '【四问小便】一天几次？颜色？量多量少？', options: ['5-7次淡黄色（正常）', '次数多量少', '次数少颜色深', '夜尿多', '小便不利', '小便黄赤', '小便清长'] },
    { key: 'thirst', question: '【五问口渴】渴不渴？想喝冷水还是热水？', options: ['不渴', '渴想喝冷水', '渴想喝热水', '渴但不想喝', '口苦口干（少阳）', '消渴（喝水不止渴）', '大渴（阳明）'] },
    { key: 'temperature', question: '【六问寒热】怕冷还是怕热？手脚温度？', options: ['手脚温热（正常）', '手脚冰冷', '手心脚心热', '头热脚冷', '上半身热下半身冷', '全身怕冷', '往来寒热（忽冷忽热）'] },
    { key: 'sweating', question: '【七问汗】容易出汗吗？什么时间出汗？', options: ['不容易出汗', '稍微活动就出汗', '睡觉出汗（盗汗）', '白天也出汗（自汗）', '但头汗出', '手足汗出', '大汗出（阳明）'] },
    { key: 'energy', question: '【八问精神】精神体力怎样？有没有特殊感觉？', options: ['精力充沛', '容易疲倦', '但欲寐（昏昏沉沉想睡）', '烦躁不安', '说话没力气', '气上撞心（感觉有气往上冲）'] },
    { key: 'pain', question: '【九问疼痛】哪里痛？什么性质的痛？', options: ['不痛', '头痛（前额）', '头痛（两侧）', '头痛（后脑）', '胸胁胀痛（少阳）', '腹痛喜按', '腹痛拒按', '关节游走痛', '身体痛+骨节痛（少阴）', '心下痞满（按之软）'] },
    { key: 'menstrual', question: '【十问月经/性功能】月经怎样？（男问性功能）', options: ['没有此症状', '月经正常', '痛经/量少/色暗有块', '月经量多/色红', '月经不调/先后无定期', '已绝经', '性功能正常', '性功能减退/腰酸'] },
  ],

  followUpQuestions: {
    '太阳': [
      { key: 'sweating', question: '【辨桂枝/麻黄】有汗还是没汗？', options: ['有汗（中风→桂枝汤）', '没汗（伤寒→麻黄汤）', '汗出不止（→桂枝加附子汤）'] },
      { key: 'neck', question: '【辨葛根汤】脖子后面僵硬吗？牵连到背部？', options: ['僵硬（→葛根汤/桂枝加葛根汤）', '不僵硬', '项背强几几+无汗（→葛根汤）'] },
      { key: 'body_pain', question: '【辨身痛类型】全身骨节酸痛吗？', options: ['全身酸痛（伤寒）', '只有头痛', '只有腰痛', '不痛', '身体疼烦不能转侧（→桂枝附子汤）', '身痒（→桂麻各半汤）'] },
      { key: 'breathing', question: '【辨喘证】有没有咳嗽气喘？', options: ['没有', '咳嗽（→桂枝加厚朴杏仁汤）', '气喘（→桂枝加厚朴杏仁汤）', '咳而上气+烦躁（→小青龙加石膏汤）', '咳嗽有白痰（→小青龙汤）', '咳嗽有黄痰（→麻杏石甘汤）'] },
      { key: 'chest', question: '【辨心下证】胸口或心下有没有不舒服？', options: ['没有', '心下满微痛（→桂去桂加苓术汤）', '心下悸（→茯苓甘草汤）', '气上冲胸（→苓桂术甘汤）'] },
      { key: 'treatment_history', question: '【辨误治】之前有没有被误用过泻药或攻下？', options: ['没有', '被误下过', '吃坏肚子拉过', '烧针令汗（→桂枝加桂汤）'] },
    ],
    '阳明': [
      { key: 'stool', question: '【辨承气汤证】大便怎样？', options: ['便秘好几天不通', '大便硬但能通（→小承气汤）', '正常', '腹泻', '便秘+腹满痛拒按+谵语（→大承气汤）', '便秘+心烦（→调胃承气汤）'] },
      { key: 'thirst', question: '【辨白虎汤证】口渴吗？想喝什么？', options: ['大渴饮冷水（→白虎加人参汤）', '口渴喝温水', '不渴', '渴+小便不利（→猪苓汤）'] },
      { key: 'sweat', question: '【辨汗出类型】出汗多吗？', options: ['大汗出（→白虎汤）', '正常', '手足汗出（→承气汤）', '但头汗出+身无汗（→茵陈蒿汤）'] },
      { key: 'abdomen', question: '【辨腹证】肚子胀不胀？按着痛不痛？', options: ['胀满拒按（不能按→大承气汤）', '胀满喜按（按着舒服）', '不胀不痛', '只胃脘痛', '腹满+身黄（→茵陈蒿汤）', '心下痞+按之濡（→大黄黄连泻心汤）'] },
      { key: 'speech', question: '【辨谵语】有没有说胡话（谵语）？', options: ['没有', '有说胡话（→承气汤）', '烦躁不安', '心中懊憹（→栀子豉汤）'] },
      { key: 'tidal_fever', question: '【辨潮热】有没有下午发冷发热（潮热）？', options: ['没有', '下午3-5点发热（潮热→大承气汤）', '全身持续发热', '手足汗出', '身黄发热（→栀子蘖皮汤）'] },
    ],
    '少阳': [
      { key: 'bitter_mouth', question: '【辨少阳主证】嘴苦吗？', options: ['嘴苦（少阳主证）', '不苦', '口苦+咽干+目眩（→小柴胡汤）'] },
      { key: 'throat', question: '【辨少阳主证】喉咙干吗？', options: ['咽干（少阳主证）', '不干', '喉咙痛', '咽干+目眩（→小柴胡汤）'] },
      { key: 'chest', question: '【辨胸胁苦满】胸口两侧胀吗？', options: ['胸胁苦满（胀痛→小柴胡汤）', '不胀', '只有胸闷', '胸胁满+微结（→柴胡桂枝干姜汤）'] },
      { key: 'nausea', question: '【辨呕吐类型】想呕吐吗？', options: ['心烦喜呕（→小柴胡汤）', '不想吐', '干呕', '呕吐不止', '呕不止+心下急（→大柴胡汤）'] },
      { key: 'eyes', question: '【辨少阳主证】眼睛有没有不舒服？', options: ['目眩（眼花→少阳主证）', '眼睛干', '没有'] },
      { key: 'constipation', question: '【辨少阳兼证】大便怎样？', options: ['正常', '便秘（少阳阳明合病→大柴胡汤/柴胡加芒硝汤）', '腹泻', '胸胁满+微结+小便不利（→柴胡桂枝干姜汤）'] },
      { key: 'extremities', question: '【辨四逆散】手脚温度？有没有烦躁？', options: ['手脚温', '手脚冷但非寒证（→四逆散）', '烦躁+身重不可转侧（→柴胡加龙骨牡蛎汤）'] },
    ],
    '太阴': [
      { key: 'appetite', question: '【辨太阴主证】胃口怎样？', options: ['吃不下（太阴主证）', '能吃但腹胀', '正常', '饿但不想吃（→理中汤）'] },
      { key: 'diarrhea', question: '【辨下利类型】大便怎样？', options: ['稀/拉肚子（太阴湿利）', '水样便', '正常', '先硬后稀', '下利不止+心下痞硬（→赤石脂禹余粮汤）'] },
      { key: 'abdomen', question: '【辨腹痛类型】肚子痛吗？', options: ['时腹自痛（隐痛→理中汤）', '腹满不痛', '不痛', '腹痛喜按', '腹满时痛（→桂枝加芍药汤）', '腹满大实痛（→桂枝加大黄汤）'] },
      { key: 'extremities', question: '【辨寒热】手脚温度怎样？', options: ['手脚冷（太阴虚寒）', '手脚温', '四肢烦疼（→桂枝附子汤）', '腹胀满+四肢倦怠（→厚朴姜夏甘参汤）'] },
      { key: 'vomiting', question: '【辨呕吐】有没有呕吐？', options: ['呕吐（太阴主证）', '不吐', '干呕', '呕吐+腹满（→理中汤）'] },
      { key: 'water_retention', question: '【辨水饮】有没有水气相关症状？', options: ['没有', '心下逆满+气上冲胸（→苓桂术甘汤）', '心下悸+厥而心下悸（→茯苓甘草汤）'] },
    ],
    '少阴': [
      { key: 'spirit', question: '【辨少阴主证】精神状态怎样？', options: ['但欲寐（昏昏沉沉想睡→少阴主证）', '精神还好', '烦躁不安（→黄连阿胶汤/热化）', '昼日烦躁夜安静（→干姜附子汤）'] },
      { key: 'extremities', question: '【辨寒化/热化】手脚温度？', options: ['冰冷（少阴寒化→四逆汤）', '温', '手脚心热（少阴热化）', '手足厥寒+脉细欲绝（→当归四逆汤）'] },
      { key: 'sleep', question: '【辨热化证】晚上能睡着吗？', options: ['心烦睡不着+舌红（→黄连阿胶汤）', '能睡', '嗜睡（寒化）', '心中烦+不得卧（→黄连阿胶汤）'] },
      { key: 'urine', question: '【辨水气证】小便怎样？', options: ['清长（肾阳虚）', '小便不利+水肿（→真武汤）', '小便黄', '正常', '小便不利+腹痛（→真武汤）'] },
      { key: 'diarrhea', question: '【辨下利类型】大便怎样？', options: ['下利清谷（完谷不化→四逆汤/通脉四逆汤）', '正常', '便秘', '便脓血（→桃花汤）', '下利+咽痛（→猪肤汤）', '下利六七日+咳而呕渴（→猪苓汤）'] },
      { key: 'pain', question: '【辨身痛证】身体有没有疼痛？', options: ['骨节疼痛（→附子汤）', '身体痛+手足寒+骨节痛+脉沉（→附子汤）', '心下悸', '没有明显疼痛', '四肢沉重疼痛（→真武汤）'] },
      { key: 'throat', question: '【辨咽痛证】喉咙怎样？', options: ['没有', '喉咙痛（→甘草汤/桔梗汤）', '咽中生疮+不能说话（→苦酒汤）', '不能说话', '咽中化脓', '咽痛+下利（→猪肤汤）'] },
      { key: 'table', question: '【辨少阴兼表】有没有发热？', options: ['没有发热', '反发热+脉沉（→麻黄附子细辛汤）', '得之二三日（→麻黄附子甘草汤）'] },
    ],
    '厥阴': [
      { key: 'thirst', question: '【辨厥阴主证】口渴吗？', options: ['消渴（喝水不止渴→厥阴主证）', '渴但不想喝', '不渴', '渴+下利（→乌梅丸）'] },
      { key: 'chest_sensation', question: '【辨气上撞心】胸口或胃有没有特殊感觉？', options: ['气上撞心（厥阴主证→乌梅丸）', '心中疼热（厥阴主证）', '没有', '干呕+吐涎沫+头痛（→吴茱萸汤）'] },
      { key: 'appetite', question: '【辨饥不欲食】饿吗？想吃东西吗？', options: ['饿但不想吃（厥阴主证→乌梅丸）', '不饿', '能吃', '食谷欲呕（→吴茱萸汤/阳明）'] },
      { key: 'extremities', question: '【辨厥证】手脚温度？', options: ['手脚冰冷（厥阴寒证）', '时冷时热（寒热错杂→乌梅丸）', '温', '手足厥寒+脉细欲绝（→当归四逆汤）'] },
      { key: 'vomiting', question: '【辨吐蛔】有没有呕吐？', options: ['食则吐蛔（→乌梅丸）', '呕吐', '不吐', '干呕+吐涎沫（→吴茱萸汤）'] },
      { key: 'stool', question: '【辨下利】大便怎样？', options: ['没有', '腹泻', '腹痛', '热利下重+便脓血（→白头翁汤）', '下利不止（→乌梅丸）', '食入口即吐（→干姜黄连黄芩人参汤）'] },
      { key: 'sputum', question: '【辨脓血】痰或唾液怎样？', options: ['没有', '白痰', '黄痰', '唾脓血（→麻黄升麻汤）'] },
    ],
  },
});
