/* 中医Buddy · 诊断规则数据 (B) — 移植自 diagnostic_rules.dart */
window.RULES = window.RULES || {};
Object.assign(window.RULES, {
  meridianDetails: {
    '太阳': { emoji: '☀️', color: '#E8804A', nature: '寒水', organ: '膀胱·小肠', keyPulse: '脉浮，头项强痛而恶寒', coreSymptoms: ['脉浮', '头项强痛', '恶寒', '发热'], healingTime: '巳至未（上午9点-下午1点）', transmissionIn: '外邪入侵第一站', transmissionOut: ['阳明', '少阳', '少阴'], classicText: '太阳之为病，脉浮，头项强痛而恶寒。（条文1）', niNote: '太阳为寒水，常人皮肤表面冰凉，手脚温热。体表有太阳寒水保卫人体。浮脉是太阳病第一症状。', formulas: ['桂枝汤', '麻黄汤', '桂枝加葛根汤', '大青龙汤', '小青龙汤', '葛根汤', '麻杏甘石汤'] },
    '阳明': { emoji: '🔥', color: '#D9544A', nature: '燥金', organ: '胃·大肠', keyPulse: '脉洪大，身热汗出，不恶寒反恶热', coreSymptoms: ['但热不寒', '身热', '汗出', '大渴', '脉洪大', '便秘'], healingTime: '申至戌（下午3点-晚上9点）', transmissionIn: ['太阳', '少阳'], transmissionOut: ['阳明无死证，病到此为止'], classicText: '阳明之为病，胃家实是也。（条文179）', niNote: '阳明病但热不寒，分经热（白虎汤）和腑实（承气汤）。阳明无死证，是最安全的经。', formulas: ['白虎汤', '白虎加人参汤', '大承气汤', '小承气汤', '调胃承气汤', '栀子豉汤'] },
    '少阳': { emoji: '🌅', color: '#E08A3C', nature: '风木', organ: '胆·三焦', keyPulse: '脉弦，口苦咽干目眩', coreSymptoms: ['口苦', '咽干', '目眩', '往来寒热', '胸胁苦满', '心烦喜呕'], healingTime: '寅至辰（凌晨3点-上午9点）', transmissionIn: ['太阳', '阳明'], transmissionOut: ['太阴', '阳明'], classicText: '少阳之为病，口苦，咽干，目眩也。（条文263）', niNote: '少阳为半表半里，位于太阳和阳明之间。但见一证便是，不必悉具。小柴胡汤是和解第一方。', formulas: ['小柴胡汤', '大柴胡汤', '柴胡加芒硝汤', '柴胡加龙骨牡蛎汤', '柴胡桂枝汤'] },
    '太阴': { emoji: '🌙', color: '#3E7CB1', nature: '湿土', organ: '脾·肺', keyPulse: '脉缓弱，腹满而吐，食不下，自利益甚', coreSymptoms: ['腹满', '呕吐', '食不下', '自利', '腹痛', '手足不温'], healingTime: '亥至丑（晚上9点-凌晨3点）', transmissionIn: ['少阳'], transmissionOut: ['少阴'], classicText: '太阴之为病，腹满而吐，食不下，自利益甚，时腹自痛。若下之，必胸下结硬。（条文273）', niNote: '太阴是脾脏，脾虚寒湿。太阴病属里虚寒证，不可攻下。理中汤是太阴病主方。', formulas: ['理中汤', '四逆汤', '小建中汤', '厚朴生姜半夏甘草人参汤', '防己黄芪汤'] },
    '少阴': { emoji: '🌑', color: '#7E5BA6', nature: '君火/寒水', organ: '心·肾', keyPulse: '脉微细，但欲寐', coreSymptoms: ['脉微细', '但欲寐', '四肢厥冷', '下利清谷', '小便清长'], healingTime: '子至寅（晚上11点-凌晨5点）', transmissionIn: ['太阴'], transmissionOut: ['厥阴'], classicText: '少阴之为病，脉微细，但欲寐也。（条文281）', niNote: '少阴是心肾阳虚，是最危险的经证之一。少阴病急温之，四逆汤为主方。分寒化和热化。', formulas: ['四逆汤', '真武汤', '附子汤', '黄连阿胶汤', '桃花汤', '麻黄附子细辛汤'] },
    '厥阴': { emoji: '☯️', color: '#5C7A8A', nature: '风木/相火', organ: '肝·心包', keyPulse: '脉弦或微欲绝，寒热错杂', coreSymptoms: ['消渴', '气上撞心', '心中疼热', '饥而不欲食', '上热下寒'], healingTime: '丑至卯（凌晨1点-早上7点）', transmissionIn: ['少阴'], transmissionOut: ['阴之尽，出则生'], classicText: '厥阴之为病，消渴，气上撞心，心中疼热，饥而不欲食，食则吐蛔，下之利不止。（条文326）', niNote: '厥阴是阴之尽，寒热并结。乌梅丸是厥阴病主方。阴阳不相顺接则为厥。厥阴病治好了会回到太阳。', formulas: ['乌梅丸', '当归四逆汤', '吴茱萸汤', '四逆散'] },
  },

  meridianHealingTime: { '太阳': '巳至未（上午9点-下午1点）', '阳明': '申至戌（下午3点-晚上9点）', '少阳': '寅至辰（凌晨3点-上午9点）', '太阴': '亥至丑（晚上9点-凌晨3点）', '少阴': '子至寅（晚上11点-凌晨5点）', '厥阴': '丑至卯（凌晨1点-早上7点）' },
  headacheLocation: { front: '阳明头痛（前额印堂痛）→ 承气汤类', side: '少阳头痛（两侧偏头痛）→ 小柴胡汤', back: '太阳头痛（后脑脖子僵）→ 葛根汤/桂枝汤', top: '厥阴头痛（头顶最痛）→ 吴茱萸汤' },
  insomniaDiagnosis: { '太阴': '脾虚失眠 → 归脾汤/小建中汤', '少阴': '心肾阳虚失眠 → 黄连阿胶汤', '厥阴': '寒热错杂失眠 → 乌梅丸', '阳明': '胃不和失眠 → 调胃承气汤' },
  constipationDiagnosis: { '热秘': '大便硬腹痛拒按 → 承气汤', '寒秘': '大便不通但腹冷喜温 → 大黄附子细辛汤', '虚秘': '无力排出 → 麻子仁丸' },

  trueFalseHeatColdData: {
    '真寒假热': { type: '真寒假热', description: '热在皮肤，寒在骨髓。外有假热象，内有真寒证。', dimensions: { '面色': '两颧色红，界限分明，红部鲜艳，不红部白中带青', '口鼻气': '呼出气不温，不急促，气不臭', '舌象': '舌虽干而质淡，或红而质润', '脉象': '脉虽浮数，按之则无力', '胸腹': '按之不蒸手，初按似热，久按不如平人', '口渴': '渴喜热饮，饮不多', '小便': '清长或不利', '大便': '稀溏或完谷不化' } },
    '真热假寒': { type: '真热假寒', description: '寒在皮肤，热在骨髓。外有假寒象，内有真热证。', dimensions: { '面色': '面色虽冷滞，两目炯炯有神', '口鼻气': '呼出气必温，急促，或有不臭', '舌象': '舌虽干而质燥，苔薄根厚，或黄而疏松', '脉象': '脉虽沉细，必兼数急', '胸腹': '四肢虽寒，胸腹必热，久按蒸蒸有热气', '口渴': '渴喜冷饮，饮多', '小便': '黄赤短少', '大便': '干结或热臭' } },
  },
  bloodStasisFiveMethods: [
    { method: '望诊', description: '面色黧黑，唇舌紫暗，舌有瘀斑瘀点，皮肤有青紫瘀斑', clinicalSignificance: '瘀血阻滞，血行不畅，面色失于濡养' },
    { method: '问诊', description: '疼痛如刺、固定不移，夜间加重，或有跌打损伤史', clinicalSignificance: '瘀血阻络，不通则痛，夜属阴故夜间加重' },
    { method: '切诊', description: '脉涩或弦紧，或有结代；腹诊可触及包块压痛', clinicalSignificance: '血行瘀滞，脉道不利' },
    { method: '望舌下', description: '舌下络脉粗胀、迂曲、色暗紫', clinicalSignificance: '舌下络脉为瘀血最直接的望诊指标' },
    { method: '望眼', description: '眼周暗黑，或白睛有赤脉络瘀曲', clinicalSignificance: '肝开窍于目，眼周暗黑为肝经瘀血' },
  ],
  facialComplexions: [
    { color: '青色', meridian: '肝/厥阴', formula: '当归四逆汤/吴茱萸汤', description: '面色青，主寒证、痛证、瘀血、惊风' },
    { color: '赤色', meridian: '阳明/少阳', formula: '白虎汤/小柴胡汤', description: '面色红，主热证。满面通红为实热，午后颧红为虚热' },
    { color: '黄色', meridian: '太阴/阳明', formula: '茵陈蒿汤/理中汤', description: '面色黄，主湿证、脾虚。鲜明为阳黄，暗淡为阴黄' },
    { color: '白色', meridian: '太阴/少阴', formula: '四逆汤/理中汤', description: '面色白，主虚证、寒证、失血。晄白为阳虚，淡白为血虚' },
    { color: '黑色', meridian: '少阴/厥阴', formula: '真武汤/肾气丸', description: '面色黑，主肾虚、寒证、痛证、瘀血、水饮' },
  ],
  medicationRules: [
    { category: '禁忌', condition: '太阳表证', prohibition: '不可攻下', reason: '表证未解先攻里，会引邪入里，导致变证', emergencyTreatment: '误下后出现痞证，用半夏泻心汤和解' },
    { category: '禁忌', condition: '阳明经热（白虎汤证）', prohibition: '不可发汗', reason: '经热已盛，发汗更伤津液，会导致谵语、烦躁', emergencyTreatment: '急下存阴，用承气汤通腑泄热' },
    { category: '禁忌', condition: '少阳病', prohibition: '不可发汗、吐、下', reason: '少阳为半表半里，汗吐下皆会导致变证', emergencyTreatment: '发汗则谵语（柴胡加龙骨牡蛎汤），吐下则悸而惊（柴胡桂枝干姜汤）' },
    { category: '禁忌', condition: '太阴虚寒证', prohibition: '不可攻下（寒凉药）', reason: '脾阳已虚，攻下更伤中阳，必致胸下结硬', emergencyTreatment: '理中汤温中健脾，或四逆汤回阳' },
    { category: '禁忌', condition: '少阴病', prohibition: '不可发汗、不可攻下', reason: '心肾阳虚，发汗亡阳，攻下亡阴', emergencyTreatment: '急温回阳，四逆汤加人参' },
    { category: '禁忌', condition: '厥阴病', prohibition: '不可单独攻下或发汗', reason: '寒热错杂，单用攻伐会加重病情', emergencyTreatment: '寒热并用，乌梅丸为主方' },
    { category: '禁忌', condition: '津液亏虚（风温/温病）', prohibition: '不可发汗、攻下、火疗', reason: '津液已亏，三法皆更伤津液，会导致直视失溲、惊痫瘛疭', emergencyTreatment: '生津液为主，白虎加人参汤' },
    { category: '误治急救', condition: '误发汗致小便不利', prohibition: '汗出过多伤津', reason: '津液亏损，化源不足', emergencyTreatment: '猪苓汤育阴利水，或五苓散通阳化气' },
    { category: '误治急救', condition: '误攻下致直视失溲', prohibition: '下法伤正，肝血枯', reason: '胃肠营养源被截断，肝血不能上注于目', emergencyTreatment: '独参汤大补元气，或四逆加人参汤' },
    { category: '误治急救', condition: '误火疗致发黄惊痫', prohibition: '火劫伤津，热入血分', reason: '火热内迫，津液枯竭，血分受热', emergencyTreatment: '茵陈蒿汤清利湿热，犀角地黄汤凉血' },
    { category: '误治急救', condition: '误吐致胃气上逆', prohibition: '吐法伤胃气', reason: '胃气因吐而虚，气逆不降', emergencyTreatment: '小半夏汤降逆止呕，或生姜半夏汤' },
    { category: '误治急救', condition: '误下致胸下结硬', prohibition: '下法伤中阳', reason: '脾阳受损，寒邪内结', emergencyTreatment: '理中汤温中散寒，或枳实薤白桂枝汤宽胸散结' },
  ],
  sweatingContraindications: [
    { condition: '阳明经热证', reason: '里热炽盛，发汗更伤津液', consequence: '大渴引饮、烦躁谵语' },
    { condition: '少阳病', reason: '半表半里，汗法不适用', consequence: '发汗则谵语（条文265）' },
    { condition: '少阴病', reason: '心肾阳虚，发汗亡阳', consequence: '四肢厥冷加重，脉微欲绝' },
    { condition: '太阴虚寒证', reason: '脾阳不足，发汗更虚', consequence: '下利不止，腹满呕吐' },
    { condition: '厥阴病', reason: '阴阳错杂，发汗扰乱气机', consequence: '上热下寒加重' },
    { condition: '咽喉干燥者', reason: '津液不足（条文83）', consequence: '小便不利，咽喉更干' },
    { condition: '淋家', reason: '膀胱津亏（条文84）', consequence: '便血' },
    { condition: '疮家', reason: '气血两虚（条文85）', consequence: '痉（筋脉拘急）' },
    { condition: '衄家', reason: '失血亡阴（条文86）', consequence: '额上陷脉紧急，直视不能眴' },
    { condition: '亡血家', reason: '气血大虚（条文87）', consequence: '寒栗而振' },
  ],
  meridianTransmissions: [
    { from: '太阳', to: '阳明', sign: '烦躁、口渴、但热不寒', treatment: '清热泻下，白虎汤/承气汤' },
    { from: '太阳', to: '少阳', sign: '口苦、咽干、呕吐、往来寒热', treatment: '和解少阳，小柴胡汤' },
    { from: '太阳', to: '少阴', sign: '但欲寐、四肢厥冷、脉微细', treatment: '急温回阳，四逆汤' },
    { from: '少阳', to: '阳明', sign: '便秘、潮热、腹满痛', treatment: '和解兼攻下，大柴胡汤/柴胡加芒硝汤' },
    { from: '太阴', to: '少阴', sign: '但欲寐加重、下利清谷', treatment: '温阳回逆，四逆汤' },
    { from: '少阴', to: '厥阴', sign: '消渴、气上撞心、寒热错杂', treatment: '寒热并用，乌梅丸' },
  ],
  pulseCombinations: [
    { pulse1: '浮', pulse2: '紧', meridian: '太阳', formula: '麻黄汤', description: '太阳伤寒表实证，无汗恶寒' },
    { pulse1: '浮', pulse2: '缓', meridian: '太阳', formula: '桂枝汤', description: '太阳中风表虚证，有汗恶风' },
    { pulse1: '浮', pulse2: '数', meridian: '太阳/阳明', formula: '桂枝二麻黄一汤/白虎汤', description: '表热或里热，需辨寒热' },
    { pulse1: '洪', pulse2: '大', meridian: '阳明', formula: '白虎汤', description: '阳明经热，大热大汗大渴' },
    { pulse1: '沉', pulse2: '迟', meridian: '少阴', formula: '四逆汤', description: '少阴寒化，阳虚寒盛' },
    { pulse1: '沉', pulse2: '细', meridian: '少阴', formula: '真武汤/附子汤', description: '少阴水饮或经脉寒湿' },
    { pulse1: '弦', pulse2: '细', meridian: '少阳', formula: '小柴胡汤', description: '少阳病，半表半里' },
    { pulse1: '弦', pulse2: '滑', meridian: '阳明/少阳', formula: '大柴胡汤', description: '少阳阳明合病，兼有里实' },
    { pulse1: '微', pulse2: '细', meridian: '少阴', formula: '四逆汤', description: '少阴病脉微细，但欲寐（条文281）' },
    { pulse1: '涩', pulse2: '弦', meridian: '厥阴', formula: '当归四逆汤', description: '血虚寒凝，脉细欲绝' },
    { pulse1: '结', pulse2: '代', meridian: '少阴', formula: '炙甘草汤', description: '气血两虚，脉结代心动悸' },
    { pulse1: '滑', pulse2: '数', meridian: '阳明', formula: '小承气汤', description: '阳明腑实，热结在里' },
  ],
  patternDifferentials: [
    { pattern1: '桂枝汤证（中风）', pattern2: '麻黄汤证（伤寒）', classicText: '太阳病，发热汗出恶风脉缓者名为中风；或已发热或未发热，必恶寒体痛呕逆脉阴阳俱紧者名曰伤寒（条文2-3）', keyPoint: '有汗vs无汗——中风有汗用桂枝，伤寒无汗用麻黄', niNote: '滤过性病毒千百种，只分这两种——按症处方就是辨症论治' },
    { pattern1: '白虎汤证（经热）', pattern2: '承气汤证（腑实）', classicText: '阳明之为病胃家实是也（条文179）', keyPoint: '经热=大热大汗大渴脉洪大（白虎）；腑实=便秘腹满痛拒按（承气）', niNote: '先辨经热还是腑实，再选方。阳明无死证。' },
    { pattern1: '小柴胡汤证', pattern2: '大柴胡汤证', classicText: '太阳病过经十余日，反二三下之，后四五日柴胡证仍在者，先与小柴胡（条文101）', keyPoint: '小柴胡=无便秘；大柴胡=兼便秘腹满（少阳阳明合病）', niNote: '大柴胡是小柴胡去人参甘草，加枳实芍药大黄。有便秘才能用大黄。' },
    { pattern1: '真武汤证', pattern2: '附子汤证', classicText: '少阴病，身体痛，手足寒，骨节痛，脉沉者，附子汤主之（条文305）', keyPoint: '真武汤=水饮（心悸头眩身瞤动）；附子汤=经脉寒湿（身体痛骨节痛）', niNote: '真武汤重在利水，附子汤重在温经散寒止痛。' },
    { pattern1: '四逆汤证', pattern2: '通脉四逆汤证', classicText: '少阴病，下利清谷，里寒外热，手足厥逆，脉微欲绝（条文317）', keyPoint: '四逆汤=一般四肢厥冷；通脉四逆=阴盛格阳（身反不恶寒、面色赤）', niNote: '通脉四逆��四逆汤重用干姜，破阴通阳。' },
    { pattern1: '苓桂术甘汤证', pattern2: '真武汤证', classicText: '伤寒若吐若下后，心下逆满，气上冲胸，起则头眩（条文67）', keyPoint: '苓桂术甘=水气上冲（轻证，脾虚水停）；真武=阳虚水泛（重证，肾阳虚）', niNote: '苓桂术甘是水在中焦，真武汤是水在下焦波及全身。' },
    { pattern1: '黄连阿胶汤证', pattern2: '栀子豉汤证', classicText: '少阴病，得之二三日以上，心中烦，不得卧（条文303）', keyPoint: '黄连阿胶=心肾不交（失眠+舌红少苔）；栀子豉=虚烦（心中懊憹+无实热）', niNote: '黄连阿胶汤有阿胶鸡子黄补心血，栀子豉汤只是清虚热。' },
    { pattern1: '五苓散证', pattern2: '猪苓汤证', classicText: '太阳病，发汗后，脉浮，小便不利，微热消渴者（条文71）', keyPoint: '五苓散=水热互结偏表（脉浮+微热）；猪苓汤=阴虚水热（血尿+口渴）', niNote: '五苓散用桂枝通阳化气，猪苓汤用阿胶育阴利水。' },
  ],
  pulseTongueContradictions: {
    '浮脉+黄厚苔': { warning: '脉浮（表证）但苔黄厚（里热），可能存在表里同病', suggestion: '需鉴别：是否太阳阳明合病？有无恶寒？' },
    '沉脉+薄白苔': { warning: '脉沉（里证）但苔薄白（正常/表证），舌脉不一致', suggestion: '可能为里证初起或表证已解，需结合问诊判断' },
    '数脉+淡白舌': { warning: '脉数（热证）但舌淡白（虚寒），寒热矛盾', suggestion: '真寒假热可能？需查：渴喜热饮？小便清长？四肢厥冷？' },
    '迟脉+红舌': { warning: '脉迟（寒证）但舌红（热证），寒热矛盾', suggestion: '真热假寒可能？需查：胸腹热？渴喜冷饮？小便黄赤？' },
    '微脉+洪脉': { warning: '脉微（虚极）与洪脉（实热）不可能同时出现', suggestion: '请重新确认脉象，或为不同部位脉象不同（寸关尺异脉）' },
  },
  quickDiagnosis: {
    '少阳': { formula: '小柴胡汤', pattern: '少阳病' },
    '阳明': { formula: '白虎汤/承气汤', pattern: '阳明病' },
    '太阴': { formula: '理中汤', pattern: '太阴病' },
    '少阴': { formula: '四逆汤', pattern: '少阴病' },
    '厥阴': { formula: '乌梅丸', pattern: '厥阴病' },
  },
});
